numInput = input('请输入算式:')
strplus = numInput.split('+')
strmin = numInput.split('-')
strmult = numInput.split('*')
strdiv = numInput.split('/')
if len(strplus)==2: print("计算结果是:",int(strplus[0])+int(strplus[1]))
elif len(strmin)==2: print("计算结果是:",int(strmin[0])-int(strmin[1]))
elif len(strmult)==2: print("计算结果是:",int(strmult[0])*int(strmult[1]))
elif len(strdiv)==2: print("计算结果是:",int(strdiv[0])/int(strdiv[1]))
else:print("请输入正确的两位数字算式")